name: garagesaleapp
description: A marketplace app

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.6
  image_picker: ^0.8.5
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.1.0

flutter:
  uses-material-design: true